routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/nova');
});

app/Models/Cuenta.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Cuenta extends Master
{
    protected $appends = ['direccion'];

    public function Provincias(){
    	return $this->belongsTo(Provincia::class);
    }

    public function Contactos(){
    	return $this->hasMany(Contacto::class,'cuentas_id');
    }
    
    protected function getActivityRefAttribute(){
		return $this->razon_social;
	}

	public function pedidos(){
		return $this->hasMany(Pedido::class,'cuentas_id');
	}

    public function getDireccionAttribute(){
        return $this->domicilio.", ".$this->localidad.", ".$this->codpos.", ".$this->Provincias->provincia;
    }
}

resources/views/pdf/compra.blade.php
<html>
	<head>
		<style>
			td, th {
				border: solid 1px black;
			}
			.sinborde {
				border: none !important;
			}
			.separador {
				height: 20px;
			}
			.etiqueta {
				font-weight: bold;
			}
			th {
				background-color: #dedede;
			}
		</style>
	</head>
	<body>
		<table align="center" width="100%" cellspacing="0">
			<tr>
				<td width="50%" class="sinborde">
					<img src="/logo-print.png">
					<div>
						<b>Pronevia s.a.</b><br>
						{{env('DOMICILIO')}}<BR>
						Tel: {{env('TELEFONO')}} / Fax: {{env('FAX')}}<br>
						CUIT: {{env('CUIT')}}
					</div>
				</td>
				<td width="50%">
					<table width="100%" cellspacing="0">
						<tr>
							<td align="center" class="sinborde">
								<h3>Órden de compra</h3>
								<div>Estado: <b>{{$fields->estado == 'A' ? 'Abierto':'Cerrada'}}</b></div>
								<h4>Número</h4>
								<div>{{$compra->id}}</div>
								<h4>Fecha</h4>
								<div>{{$compra->fecha->format('d/m/Y')}}</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td>Proveedor: {{$compra->Cuentas->activity_ref}}</td>
				<td>Código: {{$compra->Cuentas->codigo}}</td>
			</tr>
			<tr>
				@if($compra->Cuentas->Contactos()->count() > 0)
				<td>Contacto: {{$compra->Cuentas->Contactos()->first()->nombre}}</td>
				<td>Email: {{$compra->Cuentas->Contactos()->first()->email}}</td>
				@else
				<td>Contacto: </td>
				<td>Email: {{$compra->Cuentas->email}}</td>
				@endif
			</tr>
			<tr>
				<td>Dirección: {{$compra->Cuentas->direccion}}</td>
				<td>Teléfono: {{$compra->Cuentas->telefono}}</td>
			</tr>
			<tr>
				<td>CUIT: {{$compra->Cuentas->cuit}}</td>
				<td>Fax: {{$compra->Cuentas->fax}}</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td class="sinborde" colspan="3">
					<table width="100%" cellspacing="0">
						<thead>
							<tr>
								<th>It.</th>
								<th>Código</th>
								<th>Producto</th>
								<th>Cant.</th>
								<th>Uni.</th>
								<th>IVA</th>
								<th>Precio</th>
								<th>Importe</th>
							</tr>
						</thead>
						<tbody>
							@foreach($compra->compralinea as $linea)
							<tr>
								<td>{{$loop->iteration}}</td>
								<td>{{$linea->producto->codigo}}</td>
								<td>{{$linea->producto->descripcion}}</td>
								<td align="right">{{$linea->cantidad}}</td>
								<td>{{$linea->producto->unidad->unidad}}</td>
								<td align="right">{{$linea->iva}}%</td>
								<td align="right">{{number_format($linea->precio,2,',','.')}}</td>
								<td align="right">{{number_format($linea->subtotal,2,',','.')}}</td>
							</tr>
							@endforeach
							<tr>
								<td colspan="5">&nbsp;</td>
								<td colspan="2">Subtotal</td>
								<td align="right">{{number_format($compra->compralinea->sum("subtotal"),2,',','.')}}</td>
							</tr>							
							<tr>
								<td colspan="5">&nbsp;</td>
								<td colspan="2">IVA</td>
								<td align="right">{{number_format($compra->compralinea->sum("total_iva"),2,',','.')}}</td>
							</tr>
							<tr>
								<td colspan="5">&nbsp;</td>
								<td colspan="2">Total</td>
								<td align="right">{{number_format($compra->compralinea->sum("total"),2,',','.')}}</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td colspan="8">
					<div>
						<b>Condiciones Generales:</b>
						 <br>EN CASO DE NO RECIBIR ORDEN DE COMPRA MODIFICATORIA DE ESTA, LOS PEDIDOS POTENCIALES SE TRANSFORMARÁN EN FIRMES. 
						 <br>LOS MATERIALES REMITIDOS Y FACTURADOS DEBERAN INDICAR CLARAMENTE MEDIDA Y CÓDIGO. 
						 <br>PRESENTAR CERTIFICADOS DE FABRICACIÓN CORRESPONDIENTES.
						 <br>LOS MATERIALES SE ENTREGARAN EN EMBALAJES ADECUADOS, RESISTENTES Y MANIOBRABLES, IDENTIFICADO N° DE REMITO AL QUE CORRESPONDE, CANTIDAD, FECHA DE ENTREGA Y N° DE LOTE Y/0 CERTIFICADO SI CORRESPONDIERE. 
						 <br>CONFIRMAR LA RECEPCIÓN DE LA PRESENTE EN UN PLAZO MÁXIMO DE 2 DÍAS, CASO CONTRARIO LA DAREMOS POR ACEPTADA EN TODOS SUS TERMI NOS Y CONDICIONES.
					</div>
				</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td colspan="3" class="sinborde">
					<table width="100%" cellspacing="0">
						<tr>
							<td width="70%">
								<div><b>Condiciones de pago:</b>{{$compra->condicion_pago}}</div>
							</td>
							<td width="30%" valign="top" align="center" rowspan="2" height="160">
								<div><b>Confeccionó:</b></div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
							</td>
						</tr>
						<tr>
							<td>
								<div><b>Lugar de entrega: </b>{{$fields->entrega}}</div>
							</td>
						</tr>
						<tr>
							<td width="70%">
								<div><b>Fecha de entrega: </b>{{$fields->fecha}}</div>
							</td>
							<td width="30%" valign="top" align="center" rowspan="2" >
								<div>
								<b>Autorizo:</b>
								</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
								<div>&nbsp;</div>
							</td>
						</tr>
						<tr>
							<td>
								<div><b>Horario de recepción: </b>{{$fields->horario}}</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</body>
</html>

resources/views/pdf/pedido.blade.php
<html>
	<head>
		<style>
			td, th {
				border: solid 1px black;
			}
			.sinborde {
				border: none !important;
			}
			.separador {
				height: 20px;
			}
			.etiqueta {
				font-weight: bold;
			}
			th {
				background-color: #dedede;
			}
		</style>
	</head>
	<body>
		<table align="center" width="100%" cellspacing="0">
			<tr>
				<td width="25%" class="sinborde">
					<img src="/logo-print.png">
				</td>
				<td width="25%" align="center">
					<h3>Nota de pedido</h3>
					<div>Expreso: <b>{{$pedido->expreso ? 'Sí':'No'}}</b></div>
					<div>Estado: <b>{{$pedido->estado}}</b></div>
				</td>
				<td width="50%">
					<table width="100%" cellspacing="0">
						<tr>
							<td align="center" class="sinborde">
								<h4>Número de pedido</h4>
								<div>{{$pedido->id}}</div>
								<h4>Cliente</h4>
								<div>{{$pedido->Cuentas->activity_ref}}</div>
							</td>
							<td align="center" class="sinborde">
								<h4>Fecha de pedido</h4>
								<div>{{$pedido->fecha->format('d/m/Y')}}</div>
								<h4>Fecha de entrega</h4>
								<div>{{Carbon\Carbon::parse($fields->entrega)->format('d/m/Y')}}</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td class="sinborde" colspan="3">
					<table width="100%" cellspacing="0">
						<thead>
							<tr>
								<th>It.</th>
								<th>Código</th>
								<th>Producto</th>
								<th>Cant.</th>
								<th>Entregado</th>
								<th>Reb.</th>
								<th>Fab.</th>
							</tr>
						</thead>
						<tbody>
							@foreach($pedido->pedidolinea as $linea)
							<tr>
								<td>{{$loop->iteration}}</td>
								<td>{{$linea->producto->codigo}}</td>
								<td>{{$linea->producto->descripcion}}</td>
								<td align="right">{{$linea->cantidad}}</td>
								<td align="right">{{$linea->entregado}}</td>
								<td align="right">{{(!empty($linea->producto->Stock)) ? $linea->producto->Stock->rebabado : 0 }}</td>
								<td align="right">{{(!empty($linea->producto->Stock)) ? $linea->producto->Stock->fabrica : 0}}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</td>
			</tr>
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td colspan="3">
					<table width="100%" cellspacing="0">
						<tr>
							<td width="25%" class="sinborde etiqueta">Comentarios:</td>
							<td width="75%" class="sinborde">{{$fields->comentarios}}</td>
						</tr>
						<tr>
							<td class="sinborde etiqueta">Transporte:</td>
							<td class="sinborde">{{$fields->transporte}}</td>
						</tr>
						<tr>
							<td class="sinborde etiqueta">Cantidad de Items</td>
							<td class="sinborde">{{$pedido->pedidolinea()->count()}}</td>
						</tr>
					</table>
				</td>
			</tr>
			@if(!empty($fields->caja_1) || !empty($fields->caja_2) || !empty($fields->caja_3) || !empty($fields->caja_4) || !empty($fields->caja_5) || !empty($fields->caja_6))
			<tr><td class="separador sinborde">&nbsp;</td></tr>
			<tr>
				<td colspan="3" class="sinborde">
					<table width="100%" cellspacing="0">
						<tr>
							<td width="50%">
								@if(!empty($fields->caja_1))
								<div><b>Caja 1:</b> {{$fields->caja_1}}</div> 
								@endif
								@if(!empty($fields->caja_2))
								<div><b>Caja 2:</b> {{$fields->caja_2}}</div> 
								@endif
								@if(!empty($fields->caja_3))
								<div><b>Caja 3:</b> {{$fields->caja_3}}</div> 
								@endif
							</td>
							<td width="50%">
								@if(!empty($fields->caja_4))
								<div><b>Caja 4:</b> {{$fields->caja_4}}</div> 
								@endif
								@if(!empty($fields->caja_5))
								<div><b>Caja 5:</b> {{$fields->caja_5}}</div> 
								@endif
								@if(!empty($fields->caja_6))
								<div><b>Caja 6:</b> {{$fields->caja_6}}</div> 
								@endif
							</td>
						</tr>
						
					</table>
				</td>
			</tr>
			@endif
		</table>
	</body>
</html>